### PR TITLE
create dev area post 0.1.5 release

### PR DESCRIPTION
**Pull request by bewest**
Release planning happens here. :smiley_cat:

### CODE REVIEW

**Comment by scottleibrand** [comment]
@bewest it appears I may not have the required PyPi maintainer permissions to be able to release a new version?  Can you check that?

**Comment by bewest** [comment]
Howdy @scottleibrand please, set up a practice/demo project/repo and go through a few release exercises.

**Comment by bewest** [comment]
Howdy, I created a simple python package here to practice with: https://github.com/openaps/stdprojectexample/pull/1

**Comment by bewest** [comment]
Thanks for doing that @oskarpearson, looks good.  I've add you on pypi for a bunch of projects including this one. :smile_cat:

**Comment by bewest** [comment]
Err, except `openaps`, this one is the only one for not not included for you in pypi, once you get some practice with `stdprojectexample` or others on pypi, I'll add openaps core as well.

**Pull request merged**
