### PR TITLE
Make read_bg_targets only ever return data in mg/dL, not mmol/L

### PR DESCRIPTION
**Pull request by oskarpearson**
The OpenAPS system universally uses mg/dL for data. This helps ensure user
safety by ensuring we never mix up mg/dL and mmol/L.

However, the read_bg_targets code would return the values in the user-selected
measurement unit.

This patch makes the openaps system only ever write mg/dL to the read_bg_targets
file, and then stores the user-preferred value into the file.

Additionally, this change includes features to:
* Convert from mg/dL to mmol/L and vs versa
* Functions to support uniform display of mg/dL and mmol/L (by handling rounding
  appropriately, since the significant digit 6 in '5.6mmol/l' is significant,
  while the 6 in 100.6mg/dL is not signficant)

This change also introduces a testing framework into the repository, so that we
can test these functions.

### CODE REVIEW

**Comment by oskarpearson** [comment]
Of course... the tests are actually running with nosetests but on circleci and travis I get "Ran 0 tests in 0.000s"

**Comment by oskarpearson** [comment]
I've fixed the issue with tests failing to run - the primary issue was one of naming. Nosetests found the tests correctly.

I've also taken a moment to sort out the ongoing build failures with CircleCI - and migrated us to the "non-legacy" container-based builds on Travis, removing sudo.

**Comment by bewest** [comment]
Nice!

**Comment by bewest** [comment]
I love the tests, for the BG stuff, I think it should be an additional `use`, maybe for `medtronic` device, or maybe as a new `units` device?  That way if someone is using NS or something, the `units` device could be used to adjust BG targets from NS profile as well as medtronic's.

Is there a bug in decocare with reporting the right values for the given unit?
A `units` device might have `bgtargets [--to {mg/dL|mmol}]  [--from {mg/dL|mmol/L}]`, and perhaps `profile` and other things might benefit/reuse?

**Comment by oskarpearson** [comment]
@bewest Apologies for the delay here. I've been offline for a bit on holiday.

Would you consider merging this without the additional functionality? We had a problem where other code (in a private repo) would have tried to set someone's blood glucose levels to 5.5mg/dL instead of 5.5mmol/L - which would have been a pretty bad situation. The code has been changed to avoid that situation, but I'm not sure if the openaps-js code has the same problem.

I'd like to get this merged before others from the UK try and use the same code, so as to avoid any problems for them.

I think it makes sense to support converting data from one set of values to another - but since we don't use Nightscout I don't have an idea of the file formats etc. That makes it a bit difficult for me to see exactly what needs to be done.

We could change decocare to only ever report this value in mg/dL if you prefer.

Won't you let me know if I need to remove the @use() before 'class read_bg_targets' in the meantime. I'm not entirely sure what that does, to be honest! I think it makes the code available for users to call as devices via the decorator?

**Comment by bewest** [comment]
I made a compromise in short term, by giving your new one a new name, and restoring the old one, and have queued it up for merging into dev for next release.

The `@use( )` decorator adds the class to the list of exposed uses for the device, it registers them in the `openaps use <device> -h` menus.  They are basically all mini-apps.

**Comment by oskarpearson** [comment]
Closing this as it's resolved by https://github.com/openaps/openaps/pull/62

**Pull request closed without merging**
