### PR TITLE
Wip/tweak bg uses

### PR DESCRIPTION
**Pull request by bewest**
Incorporate @oskarpearson's work from https://github.com/openaps/openaps/pull/53

### CODE REVIEW

**Comment by oskarpearson** [comment]
Hey @bewest I think we're operating at cross purposes here :( it was my intention to change read_bg_targets to *always* return data in the mg/dl output.

If someone uses the read_bg_targets endpoint that's described in all the docs and from cut-and-paste examples on the internet, the default behavior of OpenAPS will be **attempt to kill** a UK & colonies user - it's going to try and set their blood sugar to 5.5mg/dl!

In my mind, all 'uses' should always return data in one set of units - mg/dL for the reasons at https://groups.google.com/forum/#!topic/openaps-dev/kt2ky41LEOs 

So I'm explicitly wanting to change the behaviour of read_bg_targets, not add a new endpoint. Adding a new endpoint/use would mean we need to change all documentation, submit addendums to all internet threads, and communicate with all potential users saying "don't copy and paste all old examples". I think that's impossible. I'd rather change the code to have safer behaviour.

If we want to add a new endpoint I'd suggest we call it read_bg_targets_mmol_l instead - so that if someone *really* wants the 'wrong' units they can get at them.

**Comment by scottleibrand** [comment]
I agree we need to get this fix merged into dev and then to master asap. Oskar is right, the only safe way to proceed is to fix the current behavior.

If there's any new functionality we don't need yet, I agree that could go into a new use, but fixing the read targets stuff to use mg/dL instead of mmol/L is definitely necessary. 

@oskarpearson: you want to also prep a PR for openaps-js and anywhere else that reads targets to set a minimum target of say 90mg/dL? That way even if someone is using a version that reads in mmol/L it will avoid setting targets dangerously low.

**Comment by bewest** [comment]
In this case, I'm going to rename `read_bg_targets` to `read_bg_targets_raw`, and keep the current one as-is.

The net effect is that copy/pasting from the broken docs won't work at all.
Perhaps someone can assist in updating the docs as well.

I think it would be very bad to give a confusing name to a use.  Openaps is intended to give you information from your pump, and then show what steps you ran to transform it.  Fetching device data AND transforming it in a single use feels like skipping steps to me.  I still prefer having an `oref0-units` tool that ensures everything it's looking at is in the right units and can convert them into the right units if needed.

**Comment by scottleibrand** [comment]
That sounds reasonable.  Is this ready for review and merge then?

**Comment by bewest** [comment]
Yeah, just renamed it as discussed.

**Comment by oskarpearson** [comment]
Thanks - I like the change to make it incompatible with bad-cut-and-pastes. Awesome. :)

**Pull request merged**
